// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWZbmftOMzJyvTioVHBqG96UTaebx-v4s',
    appId: '1:1074395857009:web:d453b5e0418b3cfdd65bd0',
    messagingSenderId: '1074395857009',
    projectId: 'flutterauth-d187b',
    authDomain: 'flutterauth-d187b.firebaseapp.com',
    storageBucket: 'flutterauth-d187b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUaINQnbtW4Y5N9oEZ36iaXw7dOI36_j0',
    appId: '1:1074395857009:android:6fdfc45aa7010d57d65bd0',
    messagingSenderId: '1074395857009',
    projectId: 'flutterauth-d187b',
    storageBucket: 'flutterauth-d187b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvL6ObzQ_dRseRckSLRILe9SaxsWPJrU',
    appId: '1:1074395857009:ios:6ac625980dbbf715d65bd0',
    messagingSenderId: '1074395857009',
    projectId: 'flutterauth-d187b',
    storageBucket: 'flutterauth-d187b.appspot.com',
    iosBundleId: 'com.example.appSederhana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWZbmftOMzJyvTioVHBqG96UTaebx-v4s',
    appId: '1:1074395857009:web:acf4f53d1da732e2d65bd0',
    messagingSenderId: '1074395857009',
    projectId: 'flutterauth-d187b',
    authDomain: 'flutterauth-d187b.firebaseapp.com',
    storageBucket: 'flutterauth-d187b.appspot.com',
  );
}
